/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package petshopsystem;

import javax.swing.JOptionPane;

/**
 *
 * @author Andrade
 */
public class AdminMenu extends javax.swing.JFrame {

    /**
     * Creates new form AdminMenu
     */
    public AdminMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtnUserSettings = new javax.swing.JButton();
        jbtnInventory = new javax.swing.JButton();
        jbtnSales = new javax.swing.JButton();
        jbtnLogout = new javax.swing.JButton();
        jbtnBuy = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ADMIN MENU");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnUserSettings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/petshopsystem/elze/usersettings.png"))); // NOI18N
        jbtnUserSettings.setBorderPainted(false);
        jbtnUserSettings.setContentAreaFilled(false);
        jbtnUserSettings.setFocusPainted(false);
        jbtnUserSettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnUserSettingsActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnUserSettings, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 200, 60));

        jbtnInventory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/petshopsystem/elze/inventory.png"))); // NOI18N
        jbtnInventory.setBorderPainted(false);
        jbtnInventory.setContentAreaFilled(false);
        jbtnInventory.setFocusPainted(false);
        jbtnInventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnInventoryActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnInventory, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 160, 50));

        jbtnSales.setIcon(new javax.swing.ImageIcon(getClass().getResource("/petshopsystem/elze/sales.png"))); // NOI18N
        jbtnSales.setBorderPainted(false);
        jbtnSales.setContentAreaFilled(false);
        jbtnSales.setFocusPainted(false);
        jbtnSales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSalesActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnSales, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 100, 50));

        jbtnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/petshopsystem/elze/logout.png"))); // NOI18N
        jbtnLogout.setBorderPainted(false);
        jbtnLogout.setContentAreaFilled(false);
        jbtnLogout.setFocusPainted(false);
        jbtnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLogoutActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, 140, 60));

        jbtnBuy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/petshopsystem/elze/buy.png"))); // NOI18N
        jbtnBuy.setBorderPainted(false);
        jbtnBuy.setContentAreaFilled(false);
        jbtnBuy.setFocusPainted(false);
        jbtnBuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBuyActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnBuy, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 80, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/petshopsystem/elze/bgbg.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnUserSettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnUserSettingsActionPerformed
        this.dispose();
        new UserSettings().setVisible(true);
    }//GEN-LAST:event_jbtnUserSettingsActionPerformed

    private void jbtnInventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnInventoryActionPerformed
        this.dispose();
        new Inventory().setVisible(true);
    }//GEN-LAST:event_jbtnInventoryActionPerformed

    private void jbtnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLogoutActionPerformed
            this.dispose();
            new LogIn().setVisible(true);
    }//GEN-LAST:event_jbtnLogoutActionPerformed

    private void jbtnSalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSalesActionPerformed
        this.dispose();
        new Sales().setVisible(true);
    }//GEN-LAST:event_jbtnSalesActionPerformed

    private void jbtnBuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBuyActionPerformed
        this.dispose();
        new Buy2().setVisible(true);
    }//GEN-LAST:event_jbtnBuyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jbtnBuy;
    private javax.swing.JButton jbtnInventory;
    private javax.swing.JButton jbtnLogout;
    private javax.swing.JButton jbtnSales;
    private javax.swing.JButton jbtnUserSettings;
    // End of variables declaration//GEN-END:variables
}
