/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package petshopsystem;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Andrade
 */
public class Buy2 extends javax.swing.JFrame {
    Connection conn = new DBConnection().connect();
    int price1 = 0,total1 = 0;
    /**
     * Creates new form Buy2
     */
    public Buy2() {
        initComponents();
        update_table();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jtfSearch = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbItems = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jtfQtyInHand = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jspQty = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        jtfPrice = new javax.swing.JTextField();
        jbtnAdd = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtbCart = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        jtfPayment = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jtfChange = new javax.swing.JTextField();
        jbtnRemove = new javax.swing.JButton();
        jbtnBuy = new javax.swing.JButton();
        jbtnClear = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jtfTotal = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtfClass = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtfDesc = new java.awt.TextArea();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BUY ITEMS/PETS");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pets & Items Available", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        jPanel1.setFocusable(false);
        jPanel1.setOpaque(false);
        jPanel1.setRequestFocusEnabled(false);
        jPanel1.setVerifyInputWhenFocusTarget(false);

        jLabel2.setText("Search:");

        jtfSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfSearchKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfSearchKeyTyped(evt);
            }
        });

        jtbItems.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jtbItems.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbItemsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtbItems);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jtfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        jLabel8.setText("Qty-in-Hand:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 70, -1, -1));

        jtfQtyInHand.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfQtyInHandKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfQtyInHandKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfQtyInHandKeyTyped(evt);
            }
        });
        getContentPane().add(jtfQtyInHand, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 70, 92, -1));

        jLabel9.setText("Qty-to-Buy:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 110, -1, -1));

        jspQty.setVerifyInputWhenFocusTarget(false);
        jspQty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jspQtyKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jspQtyKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jspQtyKeyTyped(evt);
            }
        });
        getContentPane().add(jspQty, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 110, 92, -1));

        jLabel10.setText("Price:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 150, -1, -1));

        jtfPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfPriceActionPerformed(evt);
            }
        });
        getContentPane().add(jtfPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 150, 92, -1));

        jbtnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/petshopsystem/elze/addtocart.png"))); // NOI18N
        jbtnAdd.setBorderPainted(false);
        jbtnAdd.setContentAreaFilled(false);
        jbtnAdd.setDefaultCapable(false);
        jbtnAdd.setFocusPainted(false);
        jbtnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAddActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 180, 190, 50));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pets & Items in Cart", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        jPanel2.setFocusable(false);
        jPanel2.setOpaque(false);
        jPanel2.setRequestFocusEnabled(false);
        jPanel2.setVerifyInputWhenFocusTarget(false);

        jtbCart.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Class", "Desc", "Qty", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jtbCart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbCartMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtbCart);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(259, 259, 259))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 254, 440, 184));

        jLabel14.setText("Payment:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 310, -1, -1));

        jtfPayment.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfPaymentKeyReleased(evt);
            }
        });
        getContentPane().add(jtfPayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 310, 88, -1));

        jLabel15.setText("Change:");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 350, -1, -1));
        getContentPane().add(jtfChange, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 350, 88, -1));

        jbtnRemove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/petshopsystem/elze/removefromcart.png"))); // NOI18N
        jbtnRemove.setBorderPainted(false);
        jbtnRemove.setContentAreaFilled(false);
        jbtnRemove.setFocusPainted(false);
        jbtnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRemoveActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnRemove, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 390, 290, 50));

        jbtnBuy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/petshopsystem/elze/buy.png"))); // NOI18N
        jbtnBuy.setBorderPainted(false);
        jbtnBuy.setContentAreaFilled(false);
        jbtnBuy.setFocusPainted(false);
        jbtnBuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBuyActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnBuy, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 260, 90, 50));

        jbtnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/petshopsystem/elze/clearall.png"))); // NOI18N
        jbtnClear.setBorderPainted(false);
        jbtnClear.setContentAreaFilled(false);
        jbtnClear.setFocusPainted(false);
        getContentPane().add(jbtnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 330, 150, 40));

        jLabel13.setText("Total:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 270, -1, -1));

        jtfTotal.setEnabled(false);
        getContentPane().add(jtfTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 270, 88, -1));

        jLabel3.setText("Class: ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 30, -1, -1));
        getContentPane().add(jtfClass, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 30, 92, -1));

        jLabel4.setText("Description:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 30, -1, -1));
        getContentPane().add(jtfDesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 50, 140, 120));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/petshopsystem/elze/bgbg.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 460));

        jMenuBar1.setBorderPainted(false);

        jMenu2.setText("File");

        jMenuItem2.setText("New Transaction");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem3.setText("Refresh");
        jMenu2.add(jMenuItem3);

        jMenuItem1.setText("Log out");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Edit");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void update_table() {
        String sql = "select * from itemtb";
        try {
            PreparedStatement ps = conn.prepareStatement(sql);
            
            ResultSet rs = ps.executeQuery();
            jtbItems.setModel(DbUtils.resultSetToTableModel(rs));
            //update_table();
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    private void clearText(){
        jtfClass.setText("");
        jtfQtyInHand.setText("");
        jspQty.setValue(0);
        jtfPrice.setText("");
        jtfTotal.setText("");
        jtfChange.setText("");
        jtfPayment.setText("");
    }
    private void jtbItemsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbItemsMouseClicked
        DefaultTableModel model = (DefaultTableModel) jtbItems.getModel();
        jtfClass.setText(model.getValueAt(jtbItems.getSelectedRow(), 1).toString());
        //jspQty.setValue(model.getValueAt(jtbItems.getSelectedRow(), 2));
        jtfDesc.setText(model.getValueAt(jtbItems.getSelectedRow(), 3).toString());
        jtfQtyInHand.setText(model.getValueAt(jtbItems.getSelectedRow(), 4).toString());
        jtfPrice.setText(model.getValueAt(jtbItems.getSelectedRow(), 6).toString());
        
        
    }//GEN-LAST:event_jtbItemsMouseClicked

    private void jtfPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfPriceActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        clearText();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    @SuppressWarnings("empty-statement")
    private void jbtnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAddActionPerformed
        
        int qtyInHand = Integer.parseInt(jtfQtyInHand.getText());
        int qty2 = (int) jspQty.getValue();
        if((qty2>qtyInHand)||(qty2==0)){
            JOptionPane.showMessageDialog(null, "Invalid Quantity");
        }
        
        
        else {
        String sql = "Insert into transTB (Class,Description,Qty,Total)values (?,?,?,?)";
        String sql1 = "Update itemtb set Quantity=? where Description='"+jtfDesc.getText()+"';";
        try {
            
            PreparedStatement ps = conn.prepareStatement(sql);
            PreparedStatement ps1 = conn.prepareStatement(sql1);
            int qty1 = Integer.parseInt(jtfQtyInHand.getText());
            int qty10 = (int) jspQty.getValue();
            int newQty = qty1 - qty10;
            ps1.setInt(1, newQty);
            ps1.execute();
            ps.setString(1, jtfClass.getText());
            ps.setString(2, jtfDesc.getText());
            ps.setString(3, jspQty.getValue().toString());
            int price = Integer.parseInt(jtfPrice.getText());
            int qty = (int) jspQty.getValue();
            int total = price*qty;
            ps.setInt(4, total);
            
            ps.execute();
            
            DefaultTableModel model = (DefaultTableModel) jtbCart.getModel();
            model.addRow(new Object[]{jtfClass.getText(),
            jtfDesc.getText(),jspQty.getValue(),total});
        
            JOptionPane.showMessageDialog(null, "Saved");
            
            price1 = Integer.parseInt(jtfPrice.getText());
            total1 +=total;
            
            jtfTotal.setText(String.valueOf(total1));
            
            update_table();
            
        }
        catch(SQLException | HeadlessException e){
            JOptionPane.showMessageDialog(null, e);
        }
        }
    
    }//GEN-LAST:event_jbtnAddActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        this.dispose();
        new LogIn().setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jspQtyKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jspQtyKeyTyped
        //int qty = Integer.parseInt(jtfQtyInHand.getText());
       // int qty2 = Integer.parseInt((String) jspQty.getValue());
        //int value = qty - qty2;
        //jtfQtyInHand.setText(String.valueOf(value));
    }//GEN-LAST:event_jspQtyKeyTyped

    private void jtfQtyInHandKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfQtyInHandKeyPressed
        //int qty = Integer.parseInt(jtfQtyInHand.getText());
        //int qty2 = Integer.parseInt((String) jspQty.getValue());
       // int value = qty - qty2;
       // jtfQtyInHand.setText(String.valueOf(value));
    }//GEN-LAST:event_jtfQtyInHandKeyPressed

    private void jtfQtyInHandKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfQtyInHandKeyReleased
        //int qty = Integer.parseInt(jtfQtyInHand.getText());
        //int qty2 = Integer.parseInt((String) jspQty.getValue());
        //int value = qty - qty2;
        //jtfQtyInHand.setText(String.valueOf(value));
    }//GEN-LAST:event_jtfQtyInHandKeyReleased

    private void jtfQtyInHandKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfQtyInHandKeyTyped
        //int qty = Integer.parseInt(jtfQtyInHand.getText());
        //int qty2 = Integer.parseInt((String) jspQty.getValue());
        //int value = qty - qty2;
        //jtfQtyInHand.setText(String.valueOf(value));
    }//GEN-LAST:event_jtfQtyInHandKeyTyped

    private void jspQtyKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jspQtyKeyReleased
        //int qty = Integer.parseInt(jtfQtyInHand.getText());
        //int qty2 = Integer.parseInt((String) jspQty.getValue());
        //int value = qty - qty2;
        //jtfQtyInHand.setText(String.valueOf(value));
    }//GEN-LAST:event_jspQtyKeyReleased

    private void jspQtyKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jspQtyKeyPressed
        int qty = Integer.parseInt(jtfQtyInHand.getText());
        int qty2 = Integer.parseInt((String) jspQty.getValue());
        int value = qty - qty2;
        jtfQtyInHand.setText(String.valueOf(value));
    }//GEN-LAST:event_jspQtyKeyPressed

    private void jtfSearchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfSearchKeyTyped
        
    }//GEN-LAST:event_jtfSearchKeyTyped

    private void jtfSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfSearchKeyReleased
        DefaultTableModel model = (DefaultTableModel) jtbItems.getModel();
        TableRowSorter<TableModel>sorter=new TableRowSorter<TableModel>(model);
        jtbItems.setRowSorter(sorter);
        
        String text = jtfSearch.getText();
        if(text.length()==0){
            sorter.setRowFilter(null);
        }
        else{
            sorter.setRowFilter(RowFilter.regexFilter(text));
        }
    }//GEN-LAST:event_jtfSearchKeyReleased

    private void jbtnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRemoveActionPerformed

        DefaultTableModel model = (DefaultTableModel) jtbCart.getModel();
        if(jtbCart.getSelectedRow()==-1){
            if(jtbCart.getRowCount()==0){
                JOptionPane.showMessageDialog(null, "Table is Empty");
            }else
                JOptionPane.showMessageDialog(null, "You must Select a Product");
        }
        else{
            
        try {
            String strClass = jtfDesc.getText();
            String sql ="Delete from transtb where Description='"+strClass+"';";
            PreparedStatement ps = conn.prepareStatement(sql);
            ps=conn.prepareStatement(sql);
            int total2 = (int) model.getValueAt(jtbCart.getSelectedRow(), 3);
            ps.execute();
            model.removeRow(jtbCart.getSelectedRow());
            JOptionPane.showMessageDialog(null, "Deleted");
            
            
            
            total1 -= total2;
            jtfTotal.setText(String.valueOf(total1));
        }
        catch(SQLException | HeadlessException e){
            JOptionPane.showMessageDialog(null, e);}
        }
    }//GEN-LAST:event_jbtnRemoveActionPerformed

    private void jtbCartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbCartMouseClicked
        /*update_table();
        DefaultTableModel model = (DefaultTableModel) jtbCart.getModel();
        jtfTotal.setText(model.getValueAt(jtbCart.getSelectedRow(), 3).toString());
        int t = 0;
        
        int rows = jtbCart.getRowCount();
        for(int i=0; i<=rows;i++){
            t+=(Integer)jtbCart.getValueAt(i,3);
        }
        String totalResult = Integer.toString(t);
        jtfTotal.setText(totalResult);*/
    }//GEN-LAST:event_jtbCartMouseClicked

    private void jtfPaymentKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfPaymentKeyReleased
        int total = Integer.parseInt(jtfTotal.getText());
        int payment = Integer.parseInt(jtfPayment.getText());
        int change = payment - total;
        jtfChange.setText(String.valueOf(change));
    }//GEN-LAST:event_jtfPaymentKeyReleased

    private void jbtnBuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBuyActionPerformed
        JOptionPane.showMessageDialog(null, "Transaction Complete");
        this.dispose();
        new Buy2().setVisible(true);
    }//GEN-LAST:event_jbtnBuyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Buy2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Buy2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Buy2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Buy2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Buy2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbtnAdd;
    private javax.swing.JButton jbtnBuy;
    private javax.swing.JButton jbtnClear;
    private javax.swing.JButton jbtnRemove;
    private javax.swing.JSpinner jspQty;
    private javax.swing.JTable jtbCart;
    private javax.swing.JTable jtbItems;
    private javax.swing.JTextField jtfChange;
    private javax.swing.JTextField jtfClass;
    private java.awt.TextArea jtfDesc;
    private javax.swing.JTextField jtfPayment;
    private javax.swing.JTextField jtfPrice;
    private javax.swing.JTextField jtfQtyInHand;
    private javax.swing.JTextField jtfSearch;
    private javax.swing.JTextField jtfTotal;
    // End of variables declaration//GEN-END:variables
}
