/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package petshopsystem;

import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Andrade
 */
public class LogIn extends javax.swing.JFrame {
    Connection conn = new DBConnection().connect();
    
    public LogIn() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jtfUsername = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtfPassword = new javax.swing.JPasswordField();
        jbtnLogIn = new javax.swing.JButton();
        jbtnSignUp = new javax.swing.JButton();
        jbtnCancel = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jcbUserType = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LOG IN");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Username: ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, -1, -1));

        jtfUsername.setBackground(new java.awt.Color(153, 204, 255));
        getContentPane().add(jtfUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 340, 220, -1));

        jLabel3.setText("Password:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 380, -1, -1));

        jtfPassword.setBackground(new java.awt.Color(153, 204, 255));
        getContentPane().add(jtfPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 380, 220, -1));

        jbtnLogIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/petshopsystem/elze/login.png"))); // NOI18N
        jbtnLogIn.setBorderPainted(false);
        jbtnLogIn.setContentAreaFilled(false);
        jbtnLogIn.setFocusPainted(false);
        jbtnLogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLogInActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnLogIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 270, 140, 60));

        jbtnSignUp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/petshopsystem/elze/signup.png"))); // NOI18N
        jbtnSignUp.setBorderPainted(false);
        jbtnSignUp.setContentAreaFilled(false);
        jbtnSignUp.setFocusPainted(false);
        jbtnSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSignUpActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 360, 140, 60));

        jbtnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/petshopsystem/elze/exit.png"))); // NOI18N
        jbtnCancel.setBorderPainted(false);
        jbtnCancel.setContentAreaFilled(false);
        jbtnCancel.setFocusPainted(false);
        jbtnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCancelActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 440, 140, 50));

        jLabel4.setText("Type of User: ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, -1, -1));

        jcbUserType.setBackground(new java.awt.Color(153, 204, 255));
        jcbUserType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Admin", "User" }));
        getContentPane().add(jcbUserType, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/petshopsystem/elze/happytailslogo.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/petshopsystem/elze/happytailspetshop.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, -1, 80));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/petshopsystem/elze/bgmain.png"))); // NOI18N
        jLabel1.setToolTipText("");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnLogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLogInActionPerformed
        
        String sql = "select * from usertb where username=? and password=? and usertype=?";
        try {
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setString(1, jtfUsername.getText());
            ps.setString(2, jtfPassword.getText());
            String userType = jcbUserType.getSelectedItem().toString();
            ps.setString(3, userType);
            ResultSet rs = ps.executeQuery();

            if (rs.next()) {
                JOptionPane.showMessageDialog(null, "SUCCESSFUL LOG IN");
                if(userType=="Admin"){
                    this.dispose();
                    new AdminMenu().setVisible(true);}
                else{
                    this.dispose();
                    new Buy2().setVisible(true);}
            } else {
                JOptionPane.showMessageDialog(null, "UNSUCCESSFUL LOG IN");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "ERROR" +e);
        }
    }//GEN-LAST:event_jbtnLogInActionPerformed

    private void jbtnSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSignUpActionPerformed
        this.dispose();
        new SignUp().setVisible(true);
    }//GEN-LAST:event_jbtnSignUpActionPerformed

    private void jbtnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCancelActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jbtnCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new LogIn().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton jbtnCancel;
    private javax.swing.JButton jbtnLogIn;
    private javax.swing.JButton jbtnSignUp;
    private javax.swing.JComboBox jcbUserType;
    private javax.swing.JPasswordField jtfPassword;
    private javax.swing.JTextField jtfUsername;
    // End of variables declaration//GEN-END:variables
}
