/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package petshopsystem;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Andrade
 */
public class SignUp extends javax.swing.JFrame {
    Connection conn = new DBConnection().connect();
    /**
     * Creates new form SignUp
     */
    public SignUp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jtfFname = new javax.swing.JTextField();
        jtfLname = new javax.swing.JTextField();
        jtfAddress = new javax.swing.JTextField();
        jtfContact = new javax.swing.JTextField();
        jbtnSubmit = new javax.swing.JButton();
        jbtnBack = new javax.swing.JButton();
        jcbGender = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jtfUsername = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jtfPassword = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SIGN UP");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("First Name :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel4.setText("Last Name :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jLabel5.setText("Address :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        jLabel6.setText("Contact # :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        jLabel7.setText("Gender :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        jtfFname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfFnameActionPerformed(evt);
            }
        });
        getContentPane().add(jtfFname, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 133, -1));
        getContentPane().add(jtfLname, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 134, -1));
        getContentPane().add(jtfAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 134, -1));
        getContentPane().add(jtfContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 135, -1));

        jbtnSubmit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/petshopsystem/elze/submit.png"))); // NOI18N
        jbtnSubmit.setBorderPainted(false);
        jbtnSubmit.setContentAreaFilled(false);
        jbtnSubmit.setFocusPainted(false);
        jbtnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSubmitActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 110, 40));

        jbtnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/petshopsystem/elze/back.png"))); // NOI18N
        jbtnBack.setBorderPainted(false);
        jbtnBack.setContentAreaFilled(false);
        jbtnBack.setFocusPainted(false);
        jbtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBackActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 90, 40));

        jcbGender.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female" }));
        getContentPane().add(jcbGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 135, -1));

        jLabel8.setText("Username: ");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));
        getContentPane().add(jtfUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 135, -1));

        jLabel9.setText("Password: ");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));
        getContentPane().add(jtfPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 135, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/petshopsystem/elze/bgbg.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 310));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfFnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfFnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfFnameActionPerformed

    private void jbtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBackActionPerformed
        this.dispose();
        new LogIn().setVisible(true);
    }//GEN-LAST:event_jbtnBackActionPerformed

    private void jbtnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSubmitActionPerformed
        if((jtfFname.getText().equals(""))||(jtfLname.getText()).equals("")||(jtfAddress.getText().equals(""))||(jtfContact.getText().equals(""))||(jtfUsername.getText().equals(""))||(jtfPassword.getText().equals(""))){
            JOptionPane.showMessageDialog(null, "Incomplete");
    }
        
        else {
        String sql = "Insert into usertb (username,password,usertype) values (?,?,?)";
        try {
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setString(1, jtfUsername.getText());
            ps.setString(2, jtfPassword.getText());
            ps.setString(3, "User");
            ps.execute();
            JOptionPane.showMessageDialog(null, "Saved");
            this.dispose();
            new LogIn().setVisible(true);
        }
        catch(SQLException | HeadlessException e){
            JOptionPane.showMessageDialog(null, e);
        }
        }
    }//GEN-LAST:event_jbtnSubmitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new SignUp().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton jbtnBack;
    private javax.swing.JButton jbtnSubmit;
    private javax.swing.JComboBox jcbGender;
    private javax.swing.JTextField jtfAddress;
    private javax.swing.JTextField jtfContact;
    private javax.swing.JTextField jtfFname;
    private javax.swing.JTextField jtfLname;
    private javax.swing.JPasswordField jtfPassword;
    private javax.swing.JTextField jtfUsername;
    // End of variables declaration//GEN-END:variables
}
